# Generated by Django 3.0.6 on 2020-05-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
                ('denuncia', models.CharField(max_length=10000)),
                ('edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azafran_denuncias.Edad')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azafran_denuncias.Escuela')),
            ],
        ),
    ]
