# Generated by Django 3.0.6 on 2020-07-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='ip_publica_testimonio',
            field=models.CharField(max_length=100),
        ),
    ]
