# Generated by Django 3.0.6 on 2020-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='ip_testimonio',
            new_name='ip_publica_testimonio',
        ),
    ]
