# Generated by Django 3.0.6 on 2020-07-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0003_auto_20200715_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DenunciaRecibida',
        ),
    ]
