# Generated by Django 3.0.6 on 2020-07-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0004_auto_20200727_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='ip_publica_testimonio',
            field=models.CharField(max_length=50),
        ),
    ]
