# Generated by Django 3.0.6 on 2020-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0005_denunciapublicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='denunciapublicada',
            name='escuela',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='genero',
            field=models.CharField(choices=[('', 'Selecciona un género'), ('hombre', 'Masculino'), ('mujer', 'Femenino'), ('no binario', 'No binario'), ('genero sin especificar', 'Prefiero no decirlo')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Escuela',
        ),
    ]
