# Generated by Django 3.0.6 on 2020-07-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0007_auto_20200727_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denunciapublicada',
            name='edad',
        ),
        migrations.DeleteModel(
            name='Edad',
        ),
    ]
