# Generated by Django 3.0.6 on 2020-07-27 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0009_auto_20200727_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='testimonio_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
