# Generated by Django 3.0.6 on 2020-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0012_denuncia_testimonio_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='testimonio_fecha',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='genero',
            field=models.CharField(choices=[('', 'Selecciona un género'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('No especificado', 'Prefiero no decirlo')], max_length=30),
        ),
    ]
