# Generated by Django 3.0.6 on 2020-07-27 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0013_auto_20200727_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='testimonio_fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
