# Generated by Django 3.0.6 on 2020-07-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0014_denuncia_testimonio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='ip_testimonio',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='user_agent_testimonio',
            field=models.CharField(default='Información del equipo desconocida', max_length=1000),
        ),
    ]
