# Generated by Django 3.0.6 on 2020-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azafran_denuncias', '0015_auto_20200727_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='ip_testimonio',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
